# Generated by Django 3.0.7 on 2022-04-06 17:24

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0027_department_records_readed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventtype_departments', to='department.Department')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='SmsSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispostion', models.CharField(choices=[('Arrested', 'Arrested'), ('Not Arrested', 'Not Arrested')], default='Arrested', max_length=50)),
                ('citizen_ship', models.CharField(default='victom', max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('from_field', models.CharField(default='', max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_department', to='department.Department')),
                ('eventtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.EventTypes')),
            ],
            options={
                'verbose_name': 'Sms Survey',
                'verbose_name_plural': 'Sms Surveys',
            },
        ),
        migrations.CreateModel(
            name='MessageSendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('refrence', models.CharField(blank=True, default=api.utils.create_new_ref_number, editable=False, max_length=5, unique=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_departments', to='department.Department')),
            ],
            options={
                'verbose_name': 'Message Send',
                'verbose_name_plural': 'Messages Send',
            },
        ),
    ]
