# Generated by Django 3.0.7 on 2022-04-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0027_department_records_readed'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments_database', to='department.Department')),
            ],
            options={
                'verbose_name': 'Department Database',
                'verbose_name_plural': 'Departments Databases',
            },
        ),
    ]
