# Generated by Django 3.0.7 on 2022-04-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0028_auto_20220407_0906'),
        ('events', '0002_databasedepartments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventtypes',
            unique_together={('department', 'eventtype')},
        ),
    ]
