# Generated by Django 3.0.7 on 2021-06-09 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatitudeLongitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=25)),
                ('longitude', models.CharField(blank=True, max_length=25)),
                ('zip_code', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Zip Code is not valid', regex='[0-9]{5}(-[0-9]{5})?')])),
            ],
        ),
    ]
