# Generated by Django 3.0.7 on 2020-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
