# Generated by Django 3.0.7 on 2020-06-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200620_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='profile_pic',
            field=models.ImageField(default='default_profie_pic.png', upload_to=''),
        ),
    ]
