# Generated by Django 3.0.7 on 2020-06-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200621_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='date_created',
        ),
    ]
