# Generated by Django 3.0.7 on 2020-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200621_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profie_pic.png', upload_to=''),
        ),
    ]
