# Generated by Django 3.0.7 on 2020-07-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200726_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
