# Generated by Django 3.0.7 on 2020-08-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_district'),
        ('accounts', '0020_officer_is_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.District'),
        ),
    ]
