# Generated by Django 3.0.7 on 2020-10-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_resetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetcode',
            name='created_at',
        ),
    ]
