# Generated by Django 3.0.7 on 2020-11-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_resetcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='accounts.Officer'),
        ),
        migrations.AlterField(
            model_name='log',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='accounts.Officer'),
        ),
    ]
