# Generated by Django 3.0.7 on 2020-11-10 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20201110_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_officer', to='accounts.Officer'),
        ),
        migrations.AlterField(
            model_name='log',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_by_supervisor', to='accounts.Officer'),
        ),
    ]
