# Generated by Django 3.0.7 on 2021-03-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20201110_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('notes_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_by', to='accounts.Officer')),
                ('notes_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_for', to='accounts.Officer')),
            ],
        ),
    ]
