# Generated by Django 3.0.7 on 2022-08-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_officer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='link',
            field=models.CharField(blank=True, default='9D19755CF', editable=False,
                                   max_length=10, null=True, unique=True),
        ),
    ]
