# Generated by Django 3.0.7 on 2020-06-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_should_show_as_drop_down'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='info',
            new_name='about',
        ),
    ]
