# Generated by Django 3.0.7 on 2020-06-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_departmentsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='comment_box_place_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
