# Generated by Django 3.0.7 on 2020-06-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200621_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentSurvey',
        ),
    ]
