# Generated by Django 3.0.7 on 2020-06-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_survey_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='should_show_as_drop_down',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Mutiple Choice', 'Mutiple Choice'), ('Drop Down', 'Drop Down'), ('Text Area', 'Text Area')], default='Mutiple Choice', max_length=100),
        ),
    ]
