# Generated by Django 3.0.7 on 2020-06-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20200622_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='comment_box',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='ChoiceResponse',
        ),
    ]
