# Generated by Django 3.0.7 on 2020-06-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200621_1032'),
        ('survey', '0012_auto_20200622_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Officer'),
            preserve_default=False,
        ),
    ]
