# Generated by Django 3.0.7 on 2020-06-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_surveyresponse_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='about',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(default='Sample Survey', max_length=100, unique=True),
        ),
    ]
