# Generated by Django 3.0.7 on 2020-06-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20200628_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Choice'),
        ),
    ]
