# Generated by Django 3.0.7 on 2020-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20200702_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='comment_box',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='comment_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='request_change',
            field=models.BooleanField(default=False),
        ),
    ]
