# Generated by Django 3.0.7 on 2020-07-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20200702_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='change_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='changed_by_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
