# Generated by Django 3.0.7 on 2020-07-26 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0019_auto_20200714_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
