# Generated by Django 3.0.7 on 2020-07-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200726_1605'),
        ('survey', '0021_remove_surveyresponse_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Officer'),
            preserve_default=False,
        ),
    ]
