# Generated by Django 3.0.7 on 2020-10-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_surveyresponse_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Drop Down', 'Drop Down'), ('Text Area', 'Text Area')], default='Mutiple Choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_response', to='survey.SurveyResponse'),
        ),
    ]
