# Generated by Django 3.0.7 on 2020-11-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20201008_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
