# Generated by Django 3.0.7 on 2020-11-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_callback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='notes',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='callback',
            name='notes_by_supervivor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
