# Generated by Django 3.0.7 on 2020-11-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_auto_20201121_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='comment',
        ),
    ]
