# Generated by Django 3.0.7 on 2020-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_remove_callback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
