# Generated by Django 3.0.7 on 2020-11-27 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20201110_0829'),
        ('survey', '0032_callback_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='notes_by_supervivor',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='reviewed_by_supervisor',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='CallBackNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_by_supervivor', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('callback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.CallBack')),
                ('reviewed_by_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_back_reviewed_by_supervisor', to='accounts.Officer')),
            ],
        ),
    ]
