# Generated by Django 3.0.7 on 2020-11-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_auto_20201127_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacknotes',
            name='callback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='survey.CallBack'),
        ),
    ]
