# Generated by Django 3.0.7 on 2021-01-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_questiontranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic'), ('ko', 'Korean')], default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_translation', to='survey.Question'),
        ),
        migrations.CreateModel(
            name='ChoiceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic'), ('ko', 'Korean')], default='English', max_length=100)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_translation', to='survey.Choice')),
            ],
        ),
    ]
