# Generated by Django 3.0.7 on 2021-04-14 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_employee360survey_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee360SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Employee360QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_box', models.CharField(blank=True, max_length=100)),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Employee360Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Employee360Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_response', to='survey.Employee360SurveyResponse')),
            ],
        ),
    ]
