# Generated by Django 3.0.7 on 2021-04-14 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_employee360questionresponse_employee360surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee360surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Employee360Survey'),
        ),
    ]
