# Generated by Django 3.0.7 on 2021-04-19 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_auto_20210414_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee360survey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee360survey',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee360survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
