# Generated by Django 3.0.7 on 2021-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_auto_20210423_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee360questionresponse',
            name='file',
            field=models.FileField(blank=True, upload_to='employee360Files'),
        ),
        migrations.AddField(
            model_name='employee360questionresponse',
            name='rating',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='communityquestion',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Drop Down', 'Drop Down'), ('Text Area', 'Text Area'), ('Rating', 'Rating'), ('Poll', 'Poll'), ('Vote', 'Vote'), ('Checkbox', 'Checkbox')], default='Mutiple Choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee360question',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Drop Down', 'Drop Down'), ('Text Area', 'Text Area'), ('Rating', 'Rating'), ('Poll', 'Poll'), ('Vote', 'Vote'), ('Checkbox', 'Checkbox')], default='Mutiple Choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Drop Down', 'Drop Down'), ('Text Area', 'Text Area'), ('Rating', 'Rating'), ('Poll', 'Poll'), ('Vote', 'Vote'), ('Checkbox', 'Checkbox')], default='Mutiple Choice', max_length=100),
        ),
    ]
