# Generated by Django 3.0.7 on 2021-04-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0045_auto_20210427_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityquestion',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Drop Down', 'Drop Down'), ('Text Area', 'Text Area'), ('Rating', 'Rating'), ('Poll', 'Poll'), ('Vote', 'Vote'), ('Checkbox', 'Checkbox'), ('File', 'File')], default='Mutiple Choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee360question',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Drop Down', 'Drop Down'), ('Text Area', 'Text Area'), ('Rating', 'Rating'), ('Poll', 'Poll'), ('Vote', 'Vote'), ('Checkbox', 'Checkbox'), ('File', 'File')], default='Mutiple Choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Drop Down', 'Drop Down'), ('Text Area', 'Text Area'), ('Rating', 'Rating'), ('Poll', 'Poll'), ('Vote', 'Vote'), ('Checkbox', 'Checkbox'), ('File', 'File')], default='Mutiple Choice', max_length=100),
        ),
    ]
