# Generated by Django 3.0.7 on 2021-04-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_auto_20210427_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityquestionresponse',
            name='file',
            field=models.FileField(null=True, upload_to='communityFiles'),
        ),
        migrations.AddField(
            model_name='communityquestionresponse',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
