# Generated by Django 3.0.7 on 2021-05-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0047_auto_20210427_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysurvey',
            name='type',
            field=models.CharField(choices=[('Survey', 'Survey'), ('Poll', 'Poll')], default='Survey', max_length=100),
        ),
        migrations.AddField(
            model_name='employee360survey',
            name='type',
            field=models.CharField(choices=[('Survey', 'Survey'), ('Poll', 'Poll')], default='Survey', max_length=100),
        ),
    ]
