# Generated by Django 3.0.7 on 2021-05-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_auto_20210503_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee360choice',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
