# Generated by Django 3.0.7 on 2021-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_employee360choice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychoice',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
