# Generated by Django 3.0.7 on 2021-06-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0050_communitychoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityquestionresponse',
            name='comment_box',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='employee360questionresponse',
            name='comment_box',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
