# Generated by Django 3.0.7 on 2021-06-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0051_auto_20210607_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='comment_box',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
