# Generated by Django 3.0.7 on 2021-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0053_auto_20210608_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='comment',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
