# Generated by Django 3.0.7 on 2022-03-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0026_department_is_suspend'),
        ('survey', '0054_auto_20210609_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SmsSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispostion', models.CharField(choices=[('Arrested', 'Arrested'), ('Not Arrested', 'Not Arrested')], default='Arrested', max_length=50)),
                ('citizen_ship', models.CharField(choices=[('victom', 'Victom'), ('non-victom', 'Non Victom')], default='victom', max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.EventTypes')),
            ],
        ),
    ]
