# Generated by Django 3.0.7 on 2022-03-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0026_department_is_suspend'),
        ('survey', '0055_eventtypes_smssurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssurvey',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
        migrations.AlterField(
            model_name='smssurvey',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='survey.EventTypes'),
        ),
    ]
