# Generated by Django 3.0.7 on 2022-03-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0027_department_records_readed'),
        ('survey', '0056_auto_20220308_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
            ],
        ),
    ]
