# Generated by Django 3.0.7 on 2022-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0057_messagesenddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssurvey',
            name='from_field',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
