# Generated by Django 3.0.7 on 2022-03-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0027_department_records_readed'),
        ('survey', '0058_smssurvey_from_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesenddata',
            name='event_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messagesenddata',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
