# Generated by Django 3.0.7 on 2022-03-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0059_auto_20220315_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesenddata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='smssurvey',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
