# Generated by Django 3.0.7 on 2022-03-17 07:57

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0027_department_records_readed'),
        ('survey', '0060_auto_20220316_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=sqlalchemy.sql.expression.true)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_departments', to='department.Department')),
            ],
        ),
    ]
