# Generated by Django 3.0.7 on 2022-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0061_databasedepartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssurvey',
            name='citizen_ship',
            field=models.CharField(default='victom', max_length=50),
        ),
    ]
