# Generated by Django 3.0.7 on 2022-04-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0063_auto_20220324_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtypes',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventtypes',
            name='submit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
