# Generated by Django 3.0.7 on 2022-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0064_auto_20220406_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssurvey',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smssurvey',
            name='submit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
