# Generated by Django 3.0.7 on 2022-04-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0065_auto_20220406_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtypes',
            name='department',
        ),
        migrations.RemoveField(
            model_name='messagesenddata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='smssurvey',
            name='department',
        ),
        migrations.RemoveField(
            model_name='smssurvey',
            name='eventtype',
        ),
        migrations.DeleteModel(
            name='DatabaseDepartments',
        ),
        migrations.DeleteModel(
            name='EventTypes',
        ),
        migrations.DeleteModel(
            name='MessageSendData',
        ),
        migrations.DeleteModel(
            name='SmsSurvey',
        ),
    ]
