# Generated by Django 3.0.7 on 2022-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0066_auto_20220407_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysurvey',
            name='survery_category',
            field=models.CharField(choices=[('Recuirment Survey', 'Recuirment Survey'), ('Pre-Employment Survey', 'Pre Employment Survey'), ('Onboarding Survey', 'Onboarding Survey'), ('Traning Survey', 'Traning Survey'), ('Pulse Survey', 'Pulse Survey'),
                                            ('Employee Satisfaction Survey', 'Employee Satisfaction Survey'), ('Organizational Survey', 'Organizational Survey'), ('Exit Survey', 'Exit Survey'), ('Everything Else', 'Everything Else')], default='Everything Else', max_length=50),
        ),
        migrations.AddField(
            model_name='employee360survey',
            name='survery_category',
            field=models.CharField(choices=[('Recuirment Surveys', 'Recuirment Survey'), ('Pre-Employment Surveys', 'Pre Employment Survey'), ('Onboarding Surveys', 'Onboarding Survey'), ('Traning Surveys', 'Traning Survey'), ('Pulse Surveys', 'Pulse Survey'), ('Employee Satisfaction Surveys', 'Employee Satisfaction Survey'),
                                            ('Organizational Surveys', 'Organizational Survey'), ('Exit Surveys', 'Exit Survey'), ('Mental Health Surveys', 'Mental Health Survey'), ('Police Academy Traning Surveys', 'Police Academy Traning Survey'), ('Everything Else Surveys', 'Everything Else')], default='Everything Else Surveys', max_length=50),
        ),
    ]
