# Generated by Django 3.0.7 on 2022-08-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0068_auto_20220810_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysurvey',
            name='survery_category',
            field=models.CharField(choices=[('Recuirment', 'Recuirment Survey'), ('Pre-Employment', 'Pre Employment Survey'), ('Onboarding', 'Onboarding Survey'), ('Traning', 'Traning Survey'), ('Pulse', 'Pulse Survey'), ('Employee', 'Employee Satisfaction Survey'), ('Organizational', 'Organizational Survey'), ('Exit', 'Exit Survey'), ('Mental', 'Mental Health Survey'), ('Police', 'Police Academy Traning Survey'), ('Everything', 'Everything Else')], default='Everything', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee360survey',
            name='survery_category',
            field=models.CharField(choices=[('Recuirment', 'Recuirment Survey'), ('Pre-Employment', 'Pre Employment Survey'), ('Onboarding', 'Onboarding Survey'), ('Traning', 'Traning Survey'), ('Pulse', 'Pulse Survey'), ('Employee', 'Employee Satisfaction Survey'), ('Organizational', 'Organizational Survey'), ('Exit', 'Exit Survey'), ('Mental', 'Mental Health Survey'), ('Police', 'Police Academy Traning Survey'), ('Everything', 'Everything Else')], default='Everything', max_length=50),
        ),
    ]
