# Generated by Django 3.0.7 on 2020-06-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20200622_0701'),
        ('department', '0004_department_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
