# Generated by Django 3.0.7 on 2020-06-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20200628_0537'),
        ('department', '0005_auto_20200622_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Survey'),
        ),
    ]
