# Generated by Django 3.0.7 on 2020-07-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20200705_1811'),
        ('department', '0007_auto_20200702_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
