# Generated by Django 3.0.7 on 2020-07-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20200705_1811'),
        ('department', '0008_auto_20200713_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='survey',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
            preserve_default=False,
        ),
    ]
