# Generated by Django 3.0.7 on 2020-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20200713_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='link',
            field=models.CharField(default='As', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
