# Generated by Django 3.0.7 on 2020-07-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_department_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='link',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
