# Generated by Django 3.0.7 on 2020-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='no_of_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='department',
            name='trigger_rating',
            field=models.IntegerField(default=2),
        ),
    ]
