# Generated by Django 3.0.7 on 2020-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0013_auto_20200809_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
