# Generated by Django 3.0.7 on 2020-09-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_auto_20200923_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='support'),
        ),
    ]
