# Generated by Django 3.0.7 on 2020-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0017_auto_20200923_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='support'),
        ),
    ]
