# Generated by Django 3.0.7 on 2020-12-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_auto_20200923_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='plan',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Pro', 'Pro')], default='Basic', max_length=200),
        ),
    ]
