# Generated by Django 3.0.7 on 2021-03-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0019_department_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='background',
            field=models.ImageField(default='default_background.png', upload_to='departmentBackground'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='fullName',
            field=models.CharField(blank=True, default='Department', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='departmentLogo'),
        ),
    ]
