# Generated by Django 3.0.7 on 2021-03-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0020_auto_20210308_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='background',
            field=models.ImageField(default='departmentBackground/default_background.png', upload_to='departmentBackground'),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.ImageField(default='departmentLogo/default_logo.png', upload_to='departmentLogo'),
        ),
    ]
