# Generated by Django 3.0.7 on 2021-03-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0021_auto_20210308_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
