# Generated by Django 3.0.7 on 2021-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0022_auto_20210308_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='background',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='logo',
        ),
        migrations.AddField(
            model_name='department',
            name='header',
            field=models.ImageField(default='departmentBackground/default_background.png', upload_to='departmentHeader'),
        ),
    ]
