# Generated by Django 3.0.7 on 2021-04-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0023_auto_20210317_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='header',
            field=models.ImageField(default='departmentHeader/default_background.png', upload_to='departmentHeader'),
        ),
    ]
