# Generated by Django 3.0.7 on 2021-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0024_auto_20210412_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='plan',
            field=models.CharField(blank=True, choices=[('Community', 'Community'), ('Employee', 'Employee'), ('Pro', 'Pro')], default='Basic', max_length=200),
        ),
    ]
