# Generated by Django 3.0.7 on 2022-03-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0026_department_is_suspend'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='records_readed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
