# Generated by Django 3.0.7 on 2022-04-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0027_department_records_readed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='plan',
            field=models.CharField(blank=True, choices=[('Community', 'Community'), ('Employee', 'Employee'), ('Pro', 'Pro'), ('Pro and Sms', 'Pro and Sms')], default='Basic', max_length=200),
        ),
    ]
