from django.urls import path, include
from .views.views_auth import *
from .views.views_officer import *
from .views.views_district import *
from .views.views_survey import *
from .views.view_questions import *
from .views.view_non_auth import *
from .views.view_department import *
from .views.views_admin import *
from .views.view_notes import *
from .views.views_employee360_survey import *
from .views.views_community_survey import *
from .views.view_events import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('login/', LoginViewSet.as_view(), name='login-api'),
    path('logout/', LogoutViewSet.as_view(), name='logout-api'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh-api'),
    path('me/', MeViewSet.as_view(), name='token_refresh-api'),
    path('test/', TestViewSet.as_view(), name='test-api'),
    path('officers/csv', ListOfficersCSV.as_view(), name='officer-csv-api'),
    path('officers/', ListOfficersViewSet.as_view(), name='officer-api'),
    path('officers/<int:_pk>/', ListOfficersViewSet.as_view(), name='officer-api'),
    path('officer/<int:_pk>/', DetailOfficersViewSet.as_view(),
         name='single-officer-api'),
    path('officer/<str:link>/survey', DetailOfficersSurveyViewSet.as_view(), name='officer_survey_details'),
    path('officerlogs/<int:_pk>/', OfficerLogViewSet.as_view(),
         name='single-officer-log-api'),
    path('districts/', DistrictViewSet.as_view(), name='district-api'),
    path('districts/<int:_pk>/', DistrictViewSet.as_view(), name='district-api'),
    path('survey/', SurveyViewSet.as_view(), name='survey-question-api'),
    path('surveyresponse/', SurveyResponseViewSet.as_view(),
         name='survey-response-api'),
    path('surveyresponse/<int:_pk>/', DetailSurveyResponseViewSet.as_view(),
         name='single-survey-response-api'),
    path('updatesurveyresponse/<int:_pk>/', UpdateSurveyResponseBySupervisorViewSet.as_view(),
         name='update-single-survey-response-api'),
    path('updatesurveyresponsebyofficer/<int:_pk>/', UpdateSurveyResponseByOfficerViewSet.as_view(),
         name='update-single-survey-response-officer-api'),
    path('surveyresponse/officer/<int:_pk>/',
         SurveyResponseByOfficerViewSet.as_view(), name='survey-response-officer-api'),
    path('surveyresponsebyzipcode/', SurveyResponseByZipCodeViewSet.as_view(),
         name='survey-response-zip-code-api'),
    path('support/', SupportViewSet.as_view(), name='support-api'),
    path('department/', UpdateDepartmentViewSet.as_view(), name='department-api'),
    path('needtraining/', OfficerNeedTrainingViewSet.as_view(), name='need-api'),
    path('needtraining/<int:_pk>/',
         OfficerNeedTrainingViewSet.as_view(), name='need-api'),
    path('intraining/', OfficerInTrainingViewSet.as_view(), name='in-training-api'),
    path('intraining/<int:_pk>/',
         OfficerInTrainingViewSet.as_view(), name='in-training-api'),
    path('upload-officer/', UploadOfficersViewSet.as_view(),
         name='upload-officer-api'),
    path('change-password/', UpdateOfficerPasswordViewSet.as_view(),
         name='upload-officer-password-api'),
    path('reset-password/', ResetPasswordViewSet.as_view(),
         name='reset-officer-password-api'),
    path('set-password/', SetNewPasswordViewSet.as_view(),
         name='reset-officer-password-api'),
    path('export-data/<int:_pk>/',
         GetSurveyResponseInPDF.as_view(), name='export-data-api'),
    path('call-back/', CallBackViewSet.as_view(), name='call-back-api'),
    path('call-back/<int:_pk>/',
         DetailCallBackViewSet.as_view(), name='call-back-api'),
    path('call-back-count/', CallBackCountViewSet.as_view(),
         name='call-back-count-api'),

    path('survey/questions/', QuestionViewSet.as_view(),
         name='survey-question-api'),
    path('survey/questions-reorder/', ReorderQuestionViewSet.as_view(),
         name='survey-question-reorder-api'),
    path('survey/questions/<int:_pk>/',
         QuestionViewSet.as_view(), name='survey-question-api'),

    path('department/<str:_pk>', DeparmentViewSet.as_view(), name='department-api'),
    path('departmentwithdistrict/<str:_pk>',
         DeparmentWithDistrictViewSet.as_view(), name='department-district-api'),
    path('searchofficers/<int:_pk>/', SerachOfficerInDeparmentViewSet.as_view(),
         name='search-offocer-department-api'),
    path('addsurvey/', AddSurveyResponseViewSet.as_view(),
         name='add-officer-survey-api'),
    path('signup/<int:_pk>/', SignupResponseViewSet.as_view(),
         name='signup-officer-survey-api'),
    path('requestdemo/', RequestDemoViewSet.as_view(), name='request-demo-api'),

    path('admin-login/', AdminLoginViewSet.as_view(), name='admin-login-api'),
    path('all-departments/', DepartmentViewSet.as_view(),
         name='admin-departments-api'),
    path('survey-responses-by-department/<str:_pk>',
         SurveyResponseByDepartmentViewSet.as_view(), name='admin-department-survey-api'),
    path('officer-by-department/<str:_pk>',
         AdminListOfficersViewSet.as_view(), name='admin-department-officer-api'),
    path('district-by-department/<str:_pk>',
         AdminDistrictViewSet.as_view(), name='admin-department-district-api'),
    path('notes', NotesViewSet.as_view(), name='notes-api-post'),
    path('notes/<str:_pk>', NotesViewSet.as_view(), name='notes-api-delete'),
    path('notes/', NotesViewSet.as_view(), name='notes-api-get'),
    path('edit-notes/<str:_pk>', NotesViewSet.as_view(), name='notes-api-edit'),
    path('notes-officer/<str:_pk>',
         NotesForSupervisorViewSet.as_view(), name='notes-api-post'),
    path('get-notes/<str:_pk>/',
         NotesForSupervisorViewSet.as_view(), name='notes-api-get'),
    path('get-pdf/<str:_pk>/', ExportPdfNotesViewSet.as_view(),
         name='notes-api-getPdf'),
    path('edit-department/', UpdateDepartmentDescriptionViewSet.as_view(),
         name='department-api'),

    path('employee-survey/', Employee360SurveyViewSet.as_view(),
         name='employee-survey-api'),
    path('employee-survey/<str:_pk>', DetailEmployee360SurveyViewSet.as_view(),
         name='detail-employee-survey-api'),
    path('employee-survey-by-link/<str:_pk>',
         Employee360SurveyByLinkViewSet.as_view(), name='employee-survey-by-link-api'),
    path('employee-survey-response/', AddEmployee360SurveyRepsoneViewSet.as_view(),
         name='add-employee-survey-response-api'),
    path('employee-survey-response/<str:_pk>',
         Employee360SurveyResponseViewSet.as_view(), name='detail-employee-survey-api'),
    path('employee-survey-response-report/<str:_pk>',
         Employee360SurveyResponseReportViewSet.as_view(), name='detail-employee-report-survey-api'),
    path('export-employee-survey-response/<str:_pk>',
         ExportEmployee360SurveyViewSet.as_view(), name='export-employee-survey-api'),
    path('employee-survey-response/questions-reorder/<str:_pk>/',
         Employee360SurveyReorderViewSet.as_view(), name='employee-survey-question-reorder-api'),


    path('community-survey/', CommunitySurveyViewSet.as_view(),
         name='community-survey-api'),
    path('community-survey/<str:_pk>', DetailCommunitySurveyViewSet.as_view(),
         name='detail-community-survey-api'),
    path('community-survey-by-link/<str:_pk>',
         CommunitySurveyByLinkViewSet.as_view(), name='community-survey-by-link-api'),
    path('community-survey-response/', AddCommunitySurveyRepsoneViewSet.as_view(),
         name='add-community-survey-response-api'),
    path('community-survey-response/<str:_pk>',
         CommunitySurveyResponseViewSet.as_view(), name='detail-community-survey-api'),
    path('community-survey-response-report/<str:_pk>',
         CommunitySurveyResponseReportViewSet.as_view(), name='detail-community-report-survey-api'),
    path('export-community-survey-response/<str:_pk>',
         ExportCommunitySurveyViewSet.as_view(), name='export-community-survey-api'),
    path('community-survey-response/questions-reorder/<str:_pk>/',
         CommunitySurveyReorderViewSet.as_view(), name='community-survey-question-reorder-api'),

    path('demo-graphic-response', DemoGraphicResponseViewSet.as_view(),
         name='demo-graphic-response-api'),
    path('export-demo-graphic-response/<str:_pk>',
         DemoGraphicExportViewSet.as_view(), name='export-demo-graphic-response-api'),

    path('demo-graphic-response-officer',
         DemoGraphicResponseOfficerViewSet.as_view(), name='demo-graphic-response-api'),
    path('export-demo-graphic-response-officer/<str:_pk>',
         DemoGraphicExportOfficerViewSet.as_view(), name='export-demo-graphic-response-api'),

    path('sms-survey/smssurvey/<int:pk>', SmsSurveyview.as_view()),
    path('sms-survey/smssurvey/<int:pk>/', SmsSurveyUpdateView.as_view()),
    path('sms-survey/smssurvey', SmsSurveyListApiView.as_view()),
    path('sms-survey/smssurvey/', CreateSmsSurvey.as_view()),
    path('sms-survey/eventtype/<int:pk>/', EventTypeview.as_view()),
    path('sms-survey/eventtype', EventTypeListApiView.as_view()),
    path('sms-survey/eventtype/', CreateEventType.as_view()),
    path('sms-survey/eventtype/upload/', UploadEventJsonViewSet.as_view()),
    path('sms-survey/getmessages', SendMessageData.as_view()),
    path('sms-survey/messages', MessageSendview.as_view()),
    path('sms-survey/messages-send/count/', UpdateMessageSendData.as_view()),





]
